In [1]:
import numpy as np

In [2]:
softmax_output = [0.7, 0.1, 0.2]

In [3]:
softmax_output = np.array(softmax_output).reshape(-1, 1)

In [4]:
print(softmax_output)

[[0.7]
 [0.1]
 [0.2]]


In [5]:
# Kronecker delta function = 1 if both inputs are equal, 0 otherwise.

In [6]:
print(np.eye(softmax_output.shape[0]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
print(softmax_output * np.eye(softmax_output.shape[0]))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


In [10]:
# Easier / faster way to do this.
# If value is equal, use the value, otherwise have it be zero
print(np.diagflat(softmax_output))

[[0.7 0.  0. ]
 [0.  0.1 0. ]
 [0.  0.  0.2]]


In [11]:
print(np.dot(softmax_output, softmax_output.T))

[[0.49 0.07 0.14]
 [0.07 0.01 0.02]
 [0.14 0.02 0.04]]


In [12]:
print(np.diagflat(softmax_output) -
np.dot(softmax_output, softmax_output.T))

[[ 0.21 -0.07 -0.14]
 [-0.07  0.09 -0.02]
 [-0.14 -0.02  0.16]]


## Okay, but what does this even mean?
