
Using Activation Functions in the network.
* Step function - 0 or 1. Not granular enough
* Sigmoud - Gradual change from 0 to 1 output. Has a problem that makes
Rectified Linear looks better
* Rectified Linear - output is X when X > 0, else 0. Fast (very simple), works
well

Why even use activation? ==> Linear activation functions results in the output
being linear as well. We need some kind of nonlinear activation function. The
type of non-linear activation function is less important apparently. 



In [4]:
import numpy as np
import matplotlib.pyplot as plt
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
plt.style.use('dark_background')

In [5]:
class Layer_Dense:
    def __init__(self, n_inputs, n_nuerons):
        """
        Sets the initial weights and the biases for the given layer. This is a dense layer because all of 
        the output values are passed to the input values of the next layer
        n_input - expected number of inputs. Can be from inputs or previous layer
        n_nuerons - number of nuerons to use in the layer
        """
        self.weights = 0.10 * np.random.randn(n_inputs, n_nuerons)
        self.biases = np.zeros((1, n_nuerons))


    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [6]:
class Activation_RelU:
    def __init__(self):
        """
        Activates the nuerons
        """
        pass
    
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [7]:
class Activation_Softmax:
    def __init__(self):
        """
        Cleans up the output values so they are uniform without throwing out negative values.
        """
        pass
    
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [10]:
########################### Now put it to work #############################

X, y = spiral_data(samples=100, classes=3)

In [11]:

dense1 = Layer_Dense(2,3)
activation1 = Activation_RelU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33341435 0.33327007 0.33331558]
 [0.33349672 0.33320165 0.33330157]
 [0.33357966 0.33312857 0.3332918 ]
 [0.33361688 0.33311474 0.3332684 ]]
